### ISSUE TITLE
Can I add text to the card which gopher has

### ISSUE THREAD

**Issue by tommy-sho** [quasilyte/gopherkon#2]
Thanks for creating cute tool!!

And I have one more thing I want to do. Can anyone tell me how can I add text (ex. "Hello, world") to the card which gopher has and we can select on pose?

**Comment by quasilyte** [comment]
Right now it's impossible, but as a workaround, there is an empty card sprite for that purpose, download an image and edit it as you might like.

I think it's not hard to add arbitrary image/text insertion, so it probably will be implemented in some near future, but I'll probably make gopherkon a proper single page instead of something that reloads for every click first.
